-- =========================================================
-- VinTech Marketplace — Seed Data
-- File: 002_seed.sql
-- Run this AFTER 001_schema.sql.
-- Gives you realistic fake data to test filters/search
-- before your frontend exists.
-- Password for every seeded user is: "password123"
-- (hash below is a placeholder — see note at bottom)
-- =========================================================

-- ---------------------------------------------------------
-- CATEGORIES (with two levels: parent + subcategory)
-- ---------------------------------------------------------
INSERT INTO categories (id, name, slug, parent_id) VALUES
  ('11111111-1111-1111-1111-111111111101', 'Electronics', 'electronics', NULL),
  ('11111111-1111-1111-1111-111111111102', 'Furniture', 'furniture', NULL),
  ('11111111-1111-1111-1111-111111111103', 'Household Appliances', 'household-appliances', NULL),
  ('11111111-1111-1111-1111-111111111104', 'Vehicles', 'vehicles', NULL),
  ('11111111-1111-1111-1111-111111111105', 'Apparel', 'apparel', NULL);

INSERT INTO categories (id, name, slug, parent_id) VALUES
  ('22222222-2222-2222-2222-222222222201', 'Phones', 'phones', '11111111-1111-1111-1111-111111111101'),
  ('22222222-2222-2222-2222-222222222202', 'Laptops', 'laptops', '11111111-1111-1111-1111-111111111101'),
  ('22222222-2222-2222-2222-222222222203', 'Sofas & Chairs', 'sofas-chairs', '11111111-1111-1111-1111-111111111102'),
  ('22222222-2222-2222-2222-222222222204', 'Cars', 'cars', '11111111-1111-1111-1111-111111111104');

-- ---------------------------------------------------------
-- USERS
-- Replace password_hash values with real bcrypt hashes
-- generated by your backend once auth is built (see note at bottom).
-- ---------------------------------------------------------
INSERT INTO users (id, name, email, phone, password_hash, city, neighborhood, is_verified, rating_avg, rating_count) VALUES
  ('33333333-3333-3333-3333-333333333301', 'Bethelhem Tesfaye', 'bethelhem@example.com', '+251911000001', '$2b$10$PLACEHOLDERHASH.....................', 'Addis Ababa', 'Bole', TRUE, 4.80, 12),
  ('33333333-3333-3333-3333-333333333302', 'Yonas Alemu', 'yonas@example.com', '+251911000002', '$2b$10$PLACEHOLDERHASH.....................', 'Addis Ababa', 'Kazanchis', TRUE, 4.50, 8),
  ('33333333-3333-3333-3333-333333333303', 'Selam Girma', 'selam@example.com', '+251911000003', '$2b$10$PLACEHOLDERHASH.....................', 'Addis Ababa', 'Piassa', FALSE, 0.00, 0),
  ('33333333-3333-3333-3333-333333333304', 'Dawit Kebede', 'dawit@example.com', '+251911000004', '$2b$10$PLACEHOLDERHASH.....................', 'Adama', 'Center', TRUE, 4.20, 5);

-- ---------------------------------------------------------
-- LISTINGS
-- ---------------------------------------------------------
INSERT INTO listings (id, seller_id, category_id, title, description, price, condition, city, neighborhood, status, view_count) VALUES
  ('44444444-4444-4444-4444-444444444401', '33333333-3333-3333-3333-333333333301', '22222222-2222-2222-2222-222222222201',
   'iPhone 13 Pro, 128GB', 'Used for one year, no scratches, comes with original box and charger.', 45000.00, 'lightly_used', 'Addis Ababa', 'Bole', 'active', 132),

  ('44444444-4444-4444-4444-444444444402', '33333333-3333-3333-3333-333333333302', '22222222-2222-2222-2222-222222222202',
   'Dell XPS 13 Laptop', 'Great condition, 16GB RAM, 512GB SSD. Selling because I upgraded.', 38000.00, 'lightly_used', 'Addis Ababa', 'Kazanchis', 'active', 87),

  ('44444444-4444-4444-4444-444444444403', '33333333-3333-3333-3333-333333333303', '22222222-2222-2222-2222-222222222203',
   'Leather 3-Seater Sofa', 'Minor wear on armrest, very comfortable, must pick up.', 12000.00, 'fair_condition', 'Addis Ababa', 'Piassa', 'active', 41),

  ('44444444-4444-4444-4444-444444444404', '33333333-3333-3333-3333-333333333301', '11111111-1111-1111-1111-111111111103',
   'Brand New Blender', 'Never opened, still sealed in box, gift I did not need.', 2200.00, 'brand_new', 'Addis Ababa', 'Bole', 'active', 19),

  ('44444444-4444-4444-4444-444444444405', '33333333-3333-3333-3333-333333333304', '22222222-2222-2222-2222-222222222204',
   'Toyota Vitz 2015', 'Well maintained, full service history, new tires.', 950000.00, 'fair_condition', 'Adama', 'Center', 'active', 210),

  ('44444444-4444-4444-4444-444444444406', '33333333-3333-3333-3333-333333333302', '11111111-1111-1111-1111-111111111105',
   'Men''s Winter Jacket, Size L', 'Worn a few times, excellent condition.', 1500.00, 'lightly_used', 'Addis Ababa', 'Kazanchis', 'sold', 33);

-- ---------------------------------------------------------
-- LISTING IMAGES
-- ---------------------------------------------------------
INSERT INTO listing_images (listing_id, image_url, is_primary, sort_order) VALUES
  ('44444444-4444-4444-4444-444444444401', 'https://example-cdn.com/img/iphone13_1.jpg', TRUE, 0),
  ('44444444-4444-4444-4444-444444444401', 'https://example-cdn.com/img/iphone13_2.jpg', FALSE, 1),
  ('44444444-4444-4444-4444-444444444402', 'https://example-cdn.com/img/dellxps_1.jpg', TRUE, 0),
  ('44444444-4444-4444-4444-444444444403', 'https://example-cdn.com/img/sofa_1.jpg', TRUE, 0),
  ('44444444-4444-4444-4444-444444444405', 'https://example-cdn.com/img/vitz_1.jpg', TRUE, 0);

-- ---------------------------------------------------------
-- FAVORITES
-- ---------------------------------------------------------
INSERT INTO favorites (user_id, listing_id) VALUES
  ('33333333-3333-3333-3333-333333333302', '44444444-4444-4444-4444-444444444401'),
  ('33333333-3333-3333-3333-333333333304', '44444444-4444-4444-4444-444444444403');

-- ---------------------------------------------------------
-- CONVERSATIONS + MESSAGES
-- ---------------------------------------------------------
INSERT INTO conversations (id, listing_id, buyer_id, seller_id) VALUES
  ('55555555-5555-5555-5555-555555555501', '44444444-4444-4444-4444-444444444401', '33333333-3333-3333-3333-333333333302', '33333333-3333-3333-3333-333333333301');

INSERT INTO messages (conversation_id, sender_id, content, read_at) VALUES
  ('55555555-5555-5555-5555-555555555501', '33333333-3333-3333-3333-333333333302', 'Hi, is this still available?', now()),
  ('55555555-5555-5555-5555-555555555501', '33333333-3333-3333-3333-333333333301', 'Yes it is! Are you in Bole?', NULL);

-- ---------------------------------------------------------
-- RATINGS
-- ---------------------------------------------------------
INSERT INTO ratings (rater_id, rated_user_id, listing_id, score, comment) VALUES
  ('33333333-3333-3333-3333-333333333302', '33333333-3333-3333-3333-333333333301', '44444444-4444-4444-4444-444444444401', 5, 'Smooth transaction, item as described.');

-- ---------------------------------------------------------
-- REPORTS
-- ---------------------------------------------------------
INSERT INTO reports (reporter_id, listing_id, reason, status) VALUES
  ('33333333-3333-3333-3333-333333333304', '44444444-4444-4444-4444-444444444403', 'Suspected fake listing / price too low', 'pending');

-- =========================================================
-- NOTE on password_hash values above:
-- These are placeholder strings, NOT real bcrypt hashes —
-- they will not let you log in. Once your auth endpoint is
-- built, either:
--   1) Register real test accounts through your own API, or
--   2) Generate real hashes with: bcrypt.hashSync('password123', 10)
--      and UPDATE these rows with the real hash.
-- =========================================================
